#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u result_pepro.py "$@"

# The previous version of this file was commented-out and follows below:
#
# bash run_train.sh "$@"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # python -u training.py "$@"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # python -u finetune.py "$@"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # python -u result_pepro.py "$@"
# # # # 
# # # # 
# # # # 
# # # 
# # 
# 
